name: php-docker-compose
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./dockerfile/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - docker-network

  php:
    build:
      context: .
      dockerfile: dockerfile/php.dockerfile
    volumes:
      - ./html:/var/www/html
    networks:
      - docker-network

  phpmyadmin:
    image: phpmyadmin
    tty: true
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - docker-network
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
      PMA_PORT: 3306

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    networks:
      - docker-network
    volumes: 
      - db-data:/var/lib/mysql

networks:
  docker-network:
    driver: bridge

volumes:
  db-data:
